// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: monitor.proto

package monitor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NexusService_StreamSession_FullMethodName = "/monitor.NexusService/StreamSession"
)

// NexusServiceClient is the client API for NexusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NexusServiceClient interface {
	// Bidirectional stream
	StreamSession(ctx context.Context, opts ...grpc.CallOption) (NexusService_StreamSessionClient, error)
}

type nexusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNexusServiceClient(cc grpc.ClientConnInterface) NexusServiceClient {
	return &nexusServiceClient{cc}
}

func (c *nexusServiceClient) StreamSession(ctx context.Context, opts ...grpc.CallOption) (NexusService_StreamSessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &NexusService_ServiceDesc.Streams[0], NexusService_StreamSession_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &nexusServiceStreamSessionClient{stream}
	return x, nil
}

type NexusService_StreamSessionClient interface {
	Send(*Heartbeat) error
	Recv() (*CommandResponse, error)
	grpc.ClientStream
}

type nexusServiceStreamSessionClient struct {
	grpc.ClientStream
}

func (x *nexusServiceStreamSessionClient) Send(m *Heartbeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nexusServiceStreamSessionClient) Recv() (*CommandResponse, error) {
	m := new(CommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NexusServiceServer is the server API for NexusService service.
// All implementations must embed UnimplementedNexusServiceServer
// for forward compatibility
type NexusServiceServer interface {
	// Bidirectional stream
	StreamSession(NexusService_StreamSessionServer) error
	mustEmbedUnimplementedNexusServiceServer()
}

// UnimplementedNexusServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNexusServiceServer struct {
}

func (UnimplementedNexusServiceServer) StreamSession(NexusService_StreamSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSession not implemented")
}
func (UnimplementedNexusServiceServer) mustEmbedUnimplementedNexusServiceServer() {}

// UnsafeNexusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NexusServiceServer will
// result in compilation errors.
type UnsafeNexusServiceServer interface {
	mustEmbedUnimplementedNexusServiceServer()
}

func RegisterNexusServiceServer(s grpc.ServiceRegistrar, srv NexusServiceServer) {
	s.RegisterService(&NexusService_ServiceDesc, srv)
}

func _NexusService_StreamSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NexusServiceServer).StreamSession(&nexusServiceStreamSessionServer{stream})
}

type NexusService_StreamSessionServer interface {
	Send(*CommandResponse) error
	Recv() (*Heartbeat, error)
	grpc.ServerStream
}

type nexusServiceStreamSessionServer struct {
	grpc.ServerStream
}

func (x *nexusServiceStreamSessionServer) Send(m *CommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nexusServiceStreamSessionServer) Recv() (*Heartbeat, error) {
	m := new(Heartbeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NexusService_ServiceDesc is the grpc.ServiceDesc for NexusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NexusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.NexusService",
	HandlerType: (*NexusServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSession",
			Handler:       _NexusService_StreamSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "monitor.proto",
}
